version: '3.8'

services:
  web:
    build: .
    image: gopalgtm001/demo-django:latest
    command: bash -c "python3 manage.py makemigrations 
            && python3 manage.py migrate 
            && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8080:8000"
